#!/usr/bin/env python3

"""Generate theme and README"""

import json
from os import _exit as exit
from pathlib import Path
import sys
from pprint import pprint
import re
from string import Template

import tabulate
from tabulate import tabulate as table

tabulate.PRESERVE_WHITESPACE = True

ROOT_DIR = Path(__file__).parent.parent.absolute()
DATA_DIR = ROOT_DIR.joinpath("properties")
THEMES_DIR = ROOT_DIR.joinpath("themes")

THEME_FILENAME = "dark-cool-color-theme.json"


def abort(*args, **kwargs):
    """Print error message and exit"""
    print("\033[31mError\033[0m", *args, **kwargs, file=sys.stderr)
    exit(1)


def strip_comments(fh) -> str:
    """Return contents of fh file stripped of // style comments
    Params
    ------
    fh (file): a .read()-supporting file-like object
    """
    comment = re.compile(r"^\s*//")
    trailing= re.compile(r"\s*//.*$")

    lines = [trailing.sub("", line) for line in fh if not comment.match(line)]
    return "\n".join(lines)


def load_json(filename: str):
    """Return JSON decoded object from file in DATA_DIR or exit with error"""
    with open(DATA_DIR.joinpath(filename)) as fh:
        try:
            data = json.loads(strip_comments(fh))
        except json.decoder.JSONDecodeError as e:
            abort(f"JSON errors found -- {filename}:{e.lineno}:{e.colno}\n"
                  f"     {e.msg}")
    return data


def generate_color_markdown(filename: str) -> (str, str):
    """Generate the markdown strings to be embedded in README.tpl.md"""
    manifest = load_json(filename)
    rows, refs, markdown = [], [], ""

    color_tpl = Template("![#${hex}][${hex}] `#${hex}`")
    ref_tpl = Template("[${hex}]: https://placehold.it/20/${hex}/?text=+")

    for clr in manifest["groups"]:
        if not clr.get("readme", True):
            continue

        for key in ("element", "hex", "desc", "color-desc"):
            if not key in clr or not clr.get(key, None):
                abort(f"Missing required item: {key} from color: {clr}")

        hexc = clr["hex"].lstrip("#").upper()
        uses = ", ".join(clr.get("examples", []))
        examples = f" (ie {uses})" if uses else ""

        row = {
          'Element': clr["element"],
          'Hex': color_tpl.substitute(hex=hexc),
          'Color': clr["color-desc"].title(),
          'Description': f"{clr['desc']}{examples}",
        }
        rows.append(row)
        refs.append(ref_tpl.substitute(hex=hexc))

    return dict(
        colorTable=table(rows, headers="keys", tablefmt="github"),
        refsDefs="\n".join(refs)
    )


def generate_theme_colors(filename: str) -> dict:
    """Return colors dict for theme JSON converted from colors.jsonc"""
    manifest = load_json(filename)
    colors = {}

    # generate colors from groups
    for color in manifest["groups"]:
        for key in color["theme-colors"]:
            colors[key] = f"#{color['hex']}"

    # add individual colors
    for key, hex in manifest["individual"].items():
        colors[key] = f"#{hex}"

    return colors


def usage():
    """print usage info"""
    options = [
        ["r", "readme", "generate readme"],
        ["t", "theme", "generate theme"],
        ["a", "all", "generate all"],
        ["d", "dry-run", "avoid write actions"],
        ["v", "verbose", "preview generated theme"],
        ["h", "help", "show this help screen"],
    ]

    rows = [(f" -{short}, --{lng} ", desc) for short,lng,desc in options]

    print("\ngenerate theme from colors.jsonc and tokens.jsonc\n")
    print(table(rows, tablefmt="plain"))
    print()


def save_file(filepath, contents: str, is_dryrun: bool=False):
    """After confirming write contents to filepath

    Params
    ------
    filepath (pathlib.Path): where to write file
    contents (str): contents to write to file
    is_dryrun (bool, default=False): do nothing if True
    """
    if is_dryrun:
        return

    response = input(f"Save {filepath.name}? [y/N] ").strip().lower()
    if response not in ["y", "yes"]:
        return

    filepath.write_text(contents)


def generate_theme(is_verbose: bool, is_dryrun: bool):
    """generate and save theme file"""

    theme = {
        "name": "Dark and Cool",
        "type": "dark",
        "colors": {},
        "tokenColors": []
    }
    theme["colors"] = generate_theme_colors("colors.jsonc")
    theme["tokenColors"] = load_json("tokens.jsonc")
    contents = json.dumps(theme, indent=4)

    if is_verbose:
        pprint(theme, sort_dicts=False)

    save_file(THEMES_DIR.joinpath(THEME_FILENAME), contents, is_dryrun)


def generate_readme(is_verbose: bool, is_dryrun: bool):
    """generate README.md from colors.jsonc"""
    tpl_file = Path(ROOT_DIR).joinpath("docs", "README.tpl.md")
    tpl = Template(tpl_file.read_text())
    contents = tpl.substitute(**generate_color_markdown("colors.jsonc"))

    if is_verbose:
        print(contents)

    save_file(ROOT_DIR.joinpath("README.md"), contents, is_dryrun)


def main():
    """user interface"""

    is_verbose, is_dryrun, gen_theme, gen_readme = False, False, False, False

    if any([arg in sys.argv for arg in ["-t", "--theme", "-a", "--all"]]):
        gen_theme = True

    if any([arg in sys.argv for arg in ["-r", "--readme", "-a", "--all"]]):
        gen_readme = True

    if any([arg in sys.argv for arg in ["-v", "--verbose"]]):
        is_verbose = True

    if any([arg in sys.argv for arg in ["-d", "--dry-run"]]):
        is_dryrun = True

    if any([arg in sys.argv for arg in ["-h", "--help"]]):
        usage()
        exit(0)

    if gen_theme:
        generate_theme(is_verbose, is_dryrun)

    if gen_readme:
        generate_readme(is_verbose, is_dryrun)


if __name__ == "__main__":
    main()
